- source/packages/services/assetlibrary/docs/swagger.yml
In attempting to use the swagger.yml file to generate a Java client, several discrepancies were discovered between the swagger definition and the actual service implementation.  These changes fix some of them, but there may be others.  Will submit additional pull requests as I discover more.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Fixed paths;countQuery name; TemplateInfoList schema

- source/common/changes/@cdf/provisioning/fix_provisioning_error_handling_2021-09-21-20-50.json
- source/packages/services/provisioning/src/utils/errors.ts
The provisioning service throws a "ResourceNotFoundException" as a 500. I've seen this get thrown when trying to `deleteThing` when that thing doesn't exist in IOT core. This should probably throw a 404.
> Fix provisioning error handling

- source/common/changes/@cdf/assetlibrary/fix_allow_selection_of_neptune_db_instance_type_2021-09-21-11-49.json
- source/infrastructure/cfn-cdf-core-services-A.yaml
- source/infrastructure/cfn-cdf-core-single-stack.yaml
- source/infrastructure/deploy-core-single-stack.bash
- source/infrastructure/deploy-core.bash
- source/packages/services/assetlibrary/infrastructure/cfn-assetLibrary-parent.yaml
- source/packages/services/assetlibrary/infrastructure/cfn-neptune.yaml
- source/packages/services/assetlibrary/infrastructure/deploy-cfn.bash
The deployment scripts don't allow the user to select the Neptune DB Instance type. For those who might want to use a smaller neptune DB (like t3.medium) in dev environments to save a little money, this will be an effective way to do so.
> Allow deploy script to take Neptune DB Instance Type

- source/common/changes/@cdf/events-processor/modify-event-processor-for-user-to-set-eventid_2021-10-12-06-37.json
- source/packages/services/events-processor/src/api/events/event.service.ts
This change request is to add a feature to input eventId when user creates events. Currently eventId is created by uuid() even if a user specified eventId.
- [*] *New feature (non-breaking change which adds functionality)*
- [*] Build Verified
- [*] Bundle Verified
- [*] Lint passing
- [*] Unit tests passing
- [*] Integration tests passing
- [*] Change logs generated
> Modify event processor to allow users input eventId

- source/common/changes/@cdf/assetlibrary/fix_assetlibrary_related_groups_2021-11-04-19-25.json
- source/packages/services/assetlibrary/src/devices/devices.full.service.ts
- source/packages/services/assetlibrary/src/groups/bulkgroups.controller.ts
- source/packages/services/assetlibrary/src/groups/groups.full.dao.ts
- source/packages/services/assetlibrary/src/groups/groups.full.service.ts
- source/packages/services/assetlibrary/src/groups/groups.lite.service.ts
- source/packages/services/assetlibrary/src/groups/groups.service.ts
Removed retrieving a groups related groups when all what was needed was to check the existence of a group. Returning related groups is performing poorly where groups are supernodes - they may have hundreds of thousands, or millions, of related devices, but to return related groups the related devices still need to be read then discarded. This improvement of the query that discards the devices is to follow.
> Fix assetlibrary related groups

- source/common/changes/@cdf/events-processor/modify-notification-swagger-doc_2021-11-04-07-32.json
- source/packages/services/events-processor/docs/swagger.yml
Modify swagger doc of notification to reflect that enabled, alerted flags are currently placeholders.
> Modify notification swagger doc

- source/common/changes/@cdf/assetlibrary-client/fix_policy_service_get_policy_2021-12-13-02-04.json
- source/packages/libraries/clients/assetlibrary-client/src/client/policies.lambda.service.ts
The PolicyService getPolicy function doesn't currently use the policyId, which means it returns a list of all policies instead of a single policy. This will fix it to get a single policy
> Policy service getPolicy should use policyId

- source/common/changes/@cdf/assetlibrary-client/fix_template_enum_string_array_2022-01-06-18-50.json
- source/packages/libraries/clients/assetlibrary-client/src/client/templates.model.ts
The model of a template lists an `enum` parameter. This parameter accepts the list of acceptable values for that property, therefore, should be an `string[]` instead of just a `string`
> assetlibrary-client: Fix template enum string array

- CONTRIBUTING.md
Proposing some changes to CONTRIBUTING.md since it seems natural to look here first rather than the development quickstart. I think this would help developers become more aware of the rush commands for commits and changelogs.
I wasn't able to generate any changelogs. (I believe because CONTRIBUTING.md is not in the source folder.
> docs(misc): updating Contributing docs

- source/common/changes/@cdf/assetlibrary/main_2022-03-29-17-16.json
- source/packages/services/assetlibrary/src/groups/groups.lite.dao.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> chore: replace deprecated String.prototype.substr()

- source/packages/libraries/clients/commandandcontrol-client/package.json
fix: remove unused config-inject dependecy from commandandcontrol client
> fix: remove unused config-inject dependecy from commandandcontrol client

- source/packages/libraries/core/deployment-helper/infrastructure/cfn-deployment-helper-vpc.yaml
- source/packages/libraries/core/deployment-helper/infrastructure/cfn-deployment-helper.yaml
- source/packages/libraries/core/deployment-helper/src/customResources/appConfigOverride.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotDeviceDefender.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotEndpoint.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotEvents.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotFleetIndex.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotPolicies.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotRoleAlias.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotThingGroup.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/iotThingType.customresource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/s3PutObject.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/stackEvents.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/vpcEndpoint.customResource.ts
- source/packages/libraries/core/deployment-helper/src/customResources/vpcEndpointCheck.customResource.ts
- source/packages/libraries/core/lambda-zip/src/lambda-zip.test.ts
- source/packages/libraries/core/lambda-zip/src/lambda-zip.ts
chore: update lambda-zip util to not mark aws-sdk as external dep
tested in combination with https://github.com/aws/aws-connected-device-framework/pull/134 to confirm that aws-sdk is being bundled into lambda zips
this change is tracked in https://github.com/aws/aws-connected-device-framework/issues/135 and aims to unblock the node18 upgrade
- [NA] Change logs generated
> chore: update lambda-zip util to not mark aws-sdk as external dep

- source/packages/services/command-and-control/infrastructure/cfn-command-and-control.yml
- source/packages/services/command-and-control/src/commands/commands.service.ts
- source/packages/services/command-and-control/src/messages/messages.service.ts
- source/packages/services/command-and-control/src/messages/workflow/workflow.batchTargets.ts
- source/packages/services/command-and-control/src/messages/workflow/workflow.job.ts
- source/packages/services/command-and-control/src/messages/workflow/workflow.shadow.ts
- source/packages/services/command-and-control/src/messages/workflow/workflow.topic.ts
- source/packages/services/command-and-control/src/messages/workflow/worklow.job.spec.ts
- source/packages/services/command-and-control/src/responses/responses.dao.ts
- source/packages/services/command-and-control/src/utils/dynamoDb.util.ts
fix command-and-control integ tests by adding some missing `aws-sdk` imports and bumping up some Lambda memory sizes
- [s] CI dry-run passing
- [s] Integration tests passing locally
- [NA] Change logs generated
> chore: fix command-and-control integ tests

- .github/workflows/ci.yaml
build packages in ci workflow
The bulkcerts service tests are failing for a real reason (there's a missing env var) and the workflow exit code still isn't being caught correctly, but progress
> chore: build packages in ci workflow

- THIRD-PARTY-NOTICES.txt
- deployment/generate-attributions.sh
- deployment/third-party-notices-base.txt
Created a simple script to generate third party license notices and append them to our existing notices.
> feat: generate third party license notices and append to existing

- .vscode/launch.json
- source/cicd/integrationtestsproject_build.bash
- source/packages/services/assetlibrary-export/src/data/common.full.dao.ts
- source/packages/services/assetlibrary-export/src/utils/errors.ts
- source/packages/services/assetlibrary-export/src/utils/typeUtils.ts
- source/packages/services/assetlibrary/src/data/common.full.dao.ts
- source/packages/services/assetlibrary/src/devices/devices.full.service.ts
- source/packages/services/assetlibrary/src/groups/groups.full.service.spec.ts
- source/packages/services/assetlibrary/src/groups/groups.full.service.ts
- source/packages/services/assetlibrary/src/policies/policies.full.service.spec.ts
- source/packages/services/assetlibrary/src/policies/policies.full.service.ts
- source/packages/services/assetlibrary/src/search/search.assembler.spec.ts
- source/packages/services/assetlibrary/src/search/search.assembler.ts
- source/packages/services/assetlibrary/src/search/search.full.dao.ts
- source/packages/services/assetlibrary/src/search/search.full.service.ts
- source/packages/services/assetlibrary/src/types/types.full.service.ts
- source/packages/services/assetlibrary/src/utils/inputValidation.util.ts
- source/packages/services/assetlibrary/src/utils/typeUtils.service.spec.ts
- source/packages/services/assetlibrary/src/utils/typeUtils.ts
The changes we made to validate pagination offset and count did not catch bad input in all cases. In some, they would error on missing values even though they're optional.
This unifies the checks and conversions we need to make to those values. It also guarantees defaults for all (as a security concern, we limit the values even in the case where they're omitted to prevent a DOS).
See source/packages/services/assetlibrary/src/utils/typeUtils.ts for a full description and plans for subsequent changes.
Other changes:
- I removed `npm config set @awssolutions/cdf-integration-tests:environment $ENVIRONMENT`. NPM no longer allows adding your own values to the config, and I cannot find an example of this being used anywhere.
- I added a simple launch.json for running unit tests via VSCode for …
> fix: improve and simplify handling of pagination parameters

- source/common/changes/@cdf/greengrass2-installer-config-generators/feature-ggv2-mqtt-port-config_2022-08-10-01-53.json
- source/common/changes/@cdf/installer/feature-ggv2-mqtt-port-config_2022-08-10-01-53.json
- source/packages/services/greengrass2-installer-config-generators/src/generators/manual.generator.spec.ts
- source/packages/services/greengrass2-installer-config-generators/src/generators/manual.generator.ts
- source/packages/services/greengrass2-installer-config-generators/src/lambda_manual_handler.ts
- source/packages/services/installer/src/commands/modules/service/greengrass2InstallerConfigGenerators.ts
- source/packages/services/installer/src/models/answers.ts
For engagements where the Sitewise gateway is deployed on customer n/w, the default ports for MQTT(8883) and Greengrass data plane(8443) may not works based on the IP rules set. This PR let's the customer assign the port numbers as part of the CDF deployment prompts.
> feature: apply - Configurable port for MQTT and GGv2 Data Plane

- source/packages/libraries/core/deployment-helper/src/customResources/rotateCertificatesJob.customresource.ts
Found an issue while testing a PR. Certificate Vendor calls this with a param called CommandsFunctionName but the job is looking for FunctionName.
> fix: fix an incorrect parameter name in custom resource

- source/common/changes/@awssolutions/cdf-assetlibrary/main_2023-10-06-06-40.json
- source/packages/services/assetlibrary/src/@types/gremlin/index.d.ts
- source/packages/services/assetlibrary/src/authz/authz.full.dao.ts
- source/packages/services/assetlibrary/src/data/base.full.dao.ts
- source/packages/services/assetlibrary/src/data/common.full.dao.ts
- source/packages/services/assetlibrary/src/devices/devices.full.dao.ts
- source/packages/services/assetlibrary/src/groups/groups.full.dao.ts
- source/packages/services/assetlibrary/src/init/init.full.dao.ts
- source/packages/services/assetlibrary/src/policies/policies.full.dao.ts
- source/packages/services/assetlibrary/src/profiles/profiles.full.dao.ts
- source/packages/services/assetlibrary/src/search/search.full.dao.ts
- source/packages/services/assetlibrary/src/types/types.full.dao.ts
Modified Asset Library Lambda function to use a single connection between Lambda function and Neptune throughout the Lambda lifecycle.
According to [Neptune’s documentation](https://docs.aws.amazon.com/neptune/latest/userguide/lambda-functions.html#lambda-functions-gremlin-recommendations), when accessing Neptune from Lambda, it is recommended to create one connection through the Lambda lifecycle and reuse it between invocations.
Opening and closing a Neptune connection per query causes performance issues in a state of high throughput.
I think it would be nice to have a mechanism to retry when there is an error. Now AssetLibrary users need to check the details of the error and decide if it can retry or not.
> fix(assetlibrary): change connection life cycle between Lambda and Neptune

- source/common/config/rush/pnpm-lock.yaml
- source/common/config/rush/repo-state.json
- source/packages/services/assetlibrary/infrastructure/cfn-assetLibrary.yaml
- source/packages/services/assetlibrary/infrastructure/cfn-autoscaling-neptune.yml
- source/packages/services/assetlibrary/infrastructure/cfn-neptune.yaml
- source/packages/services/installer/src/commands/modules/service/assetLibrary.ts
- source/packages/services/installer/src/models/answers.ts
- source/packages/services/installer/src/prompts/autoscaling.prompt.ts
With this commit, user can choose to enable Neptune Autoscaling along with following configurable paramters [TargetUtilization, MinCapacity,MaxCapacity]
With this commit, user can choose to enable Neptune Autoscaling along with following configurable paramters [TargetUtilization, MinCapacity,MaxCapacity]
- [x ] *New feature (non-breaking change which adds functionality)*
- [ x] Change logs generated
> [joysl] Neptune Autoscaling

- source/packages/integration-tests/features/commandandcontrol/jobs.feature
- source/packages/integration-tests/src/step_definitions/commandandcontrol/replies.steps.ts
- source/packages/services/assetlibrary/README.md
- source/packages/services/assetlibrary/docs/templates-user.md
- source/packages/services/command-and-control/README.md
This fixes two issues that were causing command and control tests to fail.
One was error logging in commandandcontrol/replies.steps.ts would fail if it caught a standard error, which we throw in the [case of No Job](https://github.com/aws/aws-connected-device-framework/blob/main/source/packages/integration-tests/src/step_definitions/commandandcontrol/jobsTestClient.ts#L75).
The second was that the recent Ephemeral Group change has a [30 second delay](https://github.com/aws/aws-connected-device-framework/blob/main/source/packages/services/command-and-control/src/messages/workflow/workflow.createEphemeralGroup.ts#L190) on the SQS message it sends.
This is a temporary fix so that tests pass as expected, but we should do additional investigation and document why this 30 second delay is …
> Command and Control integ test fix

- .vscode/settings.json
- source/common/config/rush/pnpm-lock.yaml
- source/common/config/rush/repo-state.json
- source/packages/integration-tests/features/device-patcher/patch.feature
- source/packages/integration-tests/src/step_definitions/commandandcontrol/messages.steps.ts
- source/packages/integration-tests/src/step_definitions/device-patcher/deployment.step.ts
- source/packages/integration-tests/src/support/device_patcher_hooks.ts
- source/packages/integration-tests/src/support/greengrass2_provisioning_hooks.ts
- source/packages/libraries/core/simple-cdf-logger/package.json
- source/packages/libraries/core/simple-cdf-logger/src/index.ts
- source/packages/services/assetlibraryhistory/src/lambda_iot_rule.ts
- source/packages/services/bulkcerts/src/lambda_sns_handler.ts
- source/packages/services/command-and-control/src/lambda_shadow_command_response_handler.ts
- source/packages/services/command-and-control/src/lambda_topic_command_response_handler.ts
- source/packages/services/command-and-control/src/messages/workflow/workflow.createEphemeralGroup.ts
- source/packages/services/device-patcher/src/patch/patch.dao.ts
- source/packages/services/events-processor/src/lambda_proxy_ddbstream.ts
- source/packages/services/events-processor/src/lambda_proxy_invoke.ts
- source/packages/services/events-processor/src/lambda_sqs_proxy.ts
- source/packages/services/events-processor/src/utils/errors.util.ts
- source/packages/services/greengrass2-provisioning/README.md
- source/packages/services/greengrass2-provisioning/src/lambda_ddbstream_proxy.ts
- source/packages/services/greengrass2-provisioning/src/lambda_job_execution_proxy.ts
- source/packages/services/greengrass2-provisioning/src/lambda_sqs_proxy.ts
- source/packages/services/installer/README.md
- source/packages/services/organization-manager/src/lambda_proxy_eventbridge.ts
- Main change is to add to the device-patcher teardowns to delete the patches created in the course of the tests. There isn't a straightforward way to delete the tasks as well, but so far, those don't seem to be causing errors. We can revisit later.
- re-enabled patch.feature test because correcting the teardown should ensure that it works consistently
- config-inject added to the logger because it's required for the config values to be loaded before logger creation (log level is in configs), also reordered some imports because of this
- updated the logger to warn if the configuration hasn't been set when it's created (though that should be impossible now)
- added more specific error logging and cleaned up some typos
- updated to vscode new value for organizingImports
- [x ] *Bug fix …
> fix: correcting teardown for integ test and code cleanup

- source/common/changes/@awssolutions/cdf-assetlibrary-client/fix_assetlibrary_handle_undefined_qs_params_2024-01-24-12-52.json
- source/common/changes/@awssolutions/cdf-assetlibrary/fix_assetlibrary_handle_undefined_qs_params_2024-01-24-12-52.json
- source/packages/libraries/clients/assetlibrary-client/src/client/groups.lambda.service.ts
- source/packages/services/assetlibrary/src/groups/groups.full.service.spec.ts
- source/packages/services/assetlibrary/src/utils/typeUtils.service.spec.ts
- source/packages/services/assetlibrary/src/utils/typeUtils.ts
> Fix assetlibrary handle undefined qs params

- source/common/changes/@awssolutions/cdf-assetlibrary/fix_db_instance_type_parameter_2024-01-24-12-21.json
- source/packages/services/assetlibrary/infrastructure/cfn-neptune.yaml
> fix(assetlibrary): properly quote escaped characters in cloudformation

- source/common/changes/@awssolutions/cdf-device-monitoring/fix_device_monitoring_lambda_memory_2024-02-08-20-41.json
- source/packages/services/device-monitoring/infrastructure/cfn-device-monitoring.yml
The device monitoring lambda regularly uses ~300MB per lambda invocation. 128MB will not even run, the lambdas are timing out.
> device-monitoring: lambda memory size increase

- source/common/config/rush/pnpm-lock.yaml
- source/common/config/rush/repo-state.json
- source/packages/libraries/core/version/.eslintrc.js
- source/packages/libraries/core/version/package.json
- source/packages/libraries/core/version/scripts/compile.ts
- source/packages/libraries/core/version/src/index.ts
- source/packages/libraries/core/version/src/version.ts
- source/packages/libraries/core/version/tsconfig.json
- source/rush.json
This PR extracts the version number from `version-policies.json` file managed by rush, and makes the version number importable by other packages.
- N/A, it's a internal package
- N/A, it's a internal package
> feat: add version package to securely import the CDF version number into service code

- package.json
- source/infrastructure/lambdaLayers/openssl/README.md
Added the license declaration to the package.json (matches the LICENSE.txt file). Corrected spelling errors and file reference in the OpenSSL readme.
> chore: add license value to package.json, correct openssl readme
