aws/aws-connected-device-framework

- source/packages/services/assetlibrary-export/package.json
*Issue #, if available:*
*Description of changes:*
fixed vulnerable dependency in assetlibrary export service
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> fix(assetlibrary-export): fix vulnerable dependency

- .github/issue_template.md
- .github/pull_request_template.md
*Issue #, if available:*
*Description of changes:*
Added Issue and PR templates.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> fix(core): added issue templates

- source/packages/libraries/clients/assetlibrary-client/src/client/search.model.ts
- source/packages/libraries/clients/assetlibrary-client/src/client/templates.apigw.service.ts
- source/packages/libraries/clients/assetlibrary-client/src/client/templates.lambda.service.ts
- source/packages/libraries/clients/assetlibrary-client/src/client/templates.model.ts
*Issue #, if available:*
*Description of changes:*
Based on our usage of CDF, the following updates were made to make some of the clients function as desired (and have comparable functionality to the APIs)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Updated clients with additional pre-existing functionality

- source/common/config/rush/pnpm-lock.yaml
- source/common/config/rush/repo-state.json
This PR fixes issue with new builds failing due to outdated package lock based on another PR which fixed a vulnerability with the assetlibrary-export module.
> fix(core): update lock file

- source/common/changes/@cdf/assetlibrary-export/fix_await_neptune_close_2021-09-21-11-52.json
- source/common/changes/@cdf/assetlibrary/fix_await_neptune_close_2021-09-21-11-52.json
- source/packages/services/assetlibrary-export/src/data/base.full.dao.ts
- source/packages/services/assetlibrary-export/src/data/common.full.dao.ts
- source/packages/services/assetlibrary-export/src/devices/devices.dao.ts
- source/packages/services/assetlibrary-export/src/groups/groups.dao.ts
- source/packages/services/assetlibrary-export/src/labels/labels.dao.ts
- source/packages/services/assetlibrary-export/src/types/types.dao.ts
- source/packages/services/assetlibrary/src/authz/authz.full.dao.ts
- source/packages/services/assetlibrary/src/data/base.full.dao.ts
- source/packages/services/assetlibrary/src/data/common.full.dao.ts
- source/packages/services/assetlibrary/src/devices/devices.full.dao.ts
- source/packages/services/assetlibrary/src/groups/groups.full.dao.ts
- source/packages/services/assetlibrary/src/init/init.full.dao.ts
- source/packages/services/assetlibrary/src/policies/policies.full.dao.ts
- source/packages/services/assetlibrary/src/profiles/profiles.full.dao.ts
- source/packages/services/assetlibrary/src/search/search.full.dao.ts
- source/packages/services/assetlibrary/src/types/types.full.dao.ts
The neptune `close()` function is an async function that returns `Promise<void>`, but it's treated as non-async in the current code base. These changes will make it async and ensure it's awaited throughout the code base.
> Fix: await neptune close

- source/common/changes/@cdf/assetlibrary/fix-create-bulk-error-message_2021-10-22-08-19.json
- source/packages/services/assetlibrary/src/groups/groups.full.service.ts
- [ *] *Bug fix (non-breaking change which fixes an issue)*
- [ *] Build Verified
- [ *] Bundle Verified
- [ *] Lint passing
- [ *] Unit tests passing
- [*] Integration tests passing
- [* ] Change logs generated
> fix bulk create group error message

- source/infrastructure/bundle-core.bash
Latest pnpm had broken script execution preventing bundling.
> latest pnpm had broken script execution preventing bundling

- source/common/changes/@cdf/assetlibrary-client/fix_get_groups_include_groups_2021-11-11-15-53.json
- source/common/changes/@cdf/deployment-helper/fix_get_groups_include_groups_2021-11-11-15-53.json
- source/packages/libraries/clients/assetlibrary-client/src/client/groups.apigw.service.ts
- source/packages/libraries/clients/assetlibrary-client/src/client/groups.lambda.service.ts
- source/packages/libraries/clients/assetlibrary-client/src/client/groups.service.ts
- source/packages/libraries/core/deployment-helper/src/customResources/eventSource.customResource.ts
Added the includeGroups query string parameter to the getGroup function call
> feat(clients): added includeGroups boolean to getGroups call

- source/docs/deployment.md
Addresses https://github.com/aws/aws-connected-device-framework/issues/35
* Updates deployment docs examples to use correct and consistent flags
* Add `\` to deployment docs examples to make them valid bash commands
None of the above, documentation-only change.
Not applicable: documentation-only change.
N/A
> Fix examples in deploy docs

- source/packages/services/assetlibrary/docs/swagger.yml
Addresses #49
Adds Swagger Documentation for correct sequence of steps to assemble `/search` API requests for asset library.
None of the above, documentation only.
N/A: Documentation only.
> Documentation for url-encoding of asset library search request parameters

- source/common/changes/@cdf/assetlibrary/fix_more_neptune_instance_types_2022-02-17-01-19.json
- source/infrastructure/cfn-cdf-core-services-A.yaml
- source/infrastructure/cfn-cdf-core-single-stack.yaml
- source/infrastructure/deploy-core-single-stack.bash
- source/packages/services/assetlibrary/infrastructure/cfn-assetLibrary-parent.yaml
- source/packages/services/assetlibrary/infrastructure/cfn-neptune.yaml
Added the db.r5 instance types to the possible Neptune instance types
> assetlibrary: added r5 instances to possible neptune DB selections

- source/packages/services/device-patcher/README.md
- source/packages/services/greengrass2-provisioning/README.md
- source/packages/services/provisioning/docs/provisioning-templates.md
> docs(greengrass2-provisioning): updated ggv2 docs

- source/docs/deployment.md
- source/docs/development/prerequisites.md
> Changes to Prerequisite and Deployment 

- .github/workflows/sync.yaml
- buildspec.yml
- source/packages/services/simulation-launcher/src/containers/jmeter/infrastructure/deploy.bash
Adding internal syncronization to code commit.
> Add internal syncronization to CodeCommit

- .github/workflows/ci.yaml
- source/packages/services/assetlibrary/src/config/.env.defaults
chore: add ci github workflow to run lint and unit tests on pull requests
- [NA] Integration tests passing
- [NA] Change logs generated
> chore: add ci github workflow to run lint and unit tests on pull requests

- .github/workflows/sync.yaml
- buildspec.yml
Convert buildspec for our new process. Update the workflow to trigger on tags and force code (this is the source of truth repo).
> feat: convert buildspec for new build process

- source/packages/libraries/core/deployment-helper/package.json
chore: only package bundle.zip in deployment-helper module
> chore: only package bundle.zip in deployment-helper module

- buildspec.yml
- source/packages/libraries/core/lambda-invoke/package.json
- source/rush.json
chore: update rush.json to only publish desired external-marked packages
(base) ➜  aws-connected-device-framework git:(lcanavan/update_external_package_list) ls artifacts/npm
awssolutions-cdf-assetlibrary-0.0.0.tgz
awssolutions-cdf-assetlibrary-client-0.0.0.tgz
awssolutions-cdf-assetlibrary-export-0.0.0.tgz
awssolutions-cdf-assetlibrary-history-0.0.0.tgz
awssolutions-cdf-assetlibraryhistory-client-0.0.0.tgz
awssolutions-cdf-bulkcerts-0.0.0.tgz
awssolutions-cdf-bulkcerts-client-0.0.0.tgz
awssolutions-cdf-certificate-activator-0.0.0.tgz
awssolutions-cdf-certificate-vendor-0.0.0.tgz
awssolutions-cdf-client-request-signer-0.0.0.tgz
awssolutions-cdf-command-and-control-0.0.0.tgz
awssolutions-cdf-commandandcontrol-client-0.0.0.tgz
awssolutions-cdf-deployment-helper-0.0.0.tgz …
> chore: update rush.json to only publish desired external-marked packages

- source/packages/services/assetlibrary/src/data/model.ts
- source/packages/services/assetlibrary/src/devices/devices.controller.ts
- source/packages/services/assetlibrary/src/groups/groups.full.service.ts
- source/packages/services/assetlibrary/src/search/search.controller.ts
- source/packages/services/assetlibrary/src/search/search.full.dao.ts
- source/packages/services/assetlibrary/src/types/types.controller.ts
- source/packages/services/assetlibrary/src/utils/errors.ts
- source/packages/services/assetlibraryhistory/src/utils/errors.ts
fix: handle malformed requests in asset library module and return non-5xx responses
> fix: handle malformed requests in asset library module and return non-5xx responses

- source/packages/integration-tests/features/assetlibrary/full/groupMembers.feature
- source/packages/integration-tests/features/assetlibrary/full/groupProfiles.feature
- source/packages/integration-tests/features/assetlibrary/full/groupSearch.feature
- source/packages/integration-tests/features/assetlibraryhistory/deviceHistory.feature
- source/packages/integration-tests/src/step_definitions/assetlibrary/bulkdevices.steps.ts
- source/packages/integration-tests/src/step_definitions/assetlibraryhistory/history.steps.ts
- source/packages/integration-tests/src/support/assetLibraryHistory_hooks.ts
- source/packages/integration-tests/src/support/assetLibrary_hooks.ts
chore: add integ test coverage of authz functionality in asset library module
- [NA] Change logs generated
> chore: add integ test coverage of authz functionality in asset library module

- source/packages/integration-tests/features/device-patcher/template.feature
- source/packages/services/command-and-control/src/commands/commands.assembler.ts
- source/packages/services/events-processor/src/utils/errors.util.ts
> chore: more invalid request handling

- source/packages/libraries/clients/assetlibrary-client/src/client/groups.apigw.service.ts
fix Asset Library GroupsService listGroupRelatedDevices error handling
> fix Asset Library GroupsService listGroupRelatedDevices error handling

- source/packages/libraries/core/deployment-helper/src/customResources/rotateCertificatesJob.customresource.ts
fix: fetch CNC Lambda name from customerResource payload
> fix: fetch CNC Lambda name from customerResource payload

- .github/pull_request_template.md
chore: update PR template to mention CI passing build requirement
> chore: update PR template to mention CI passing build requirement

- .github/workflows/ci.yaml
Add bundle (which includes build) step to the CI actions
> fix: add build step to ci

- source/packages/services/simulation-manager/src/runs/runs.dao.spec.ts
- source/packages/services/simulation-manager/src/runs/runs.dao.ts
Formatting caused an eslint ignore comment to fall to the following line, which broke the unit tests. However, instead of countering the formatting, I rewrote the function as a do/while to avoid the type of danger it produces. I added a unit test for it as well.
> fix: improve device list aggregation and add unit test

- source/packages/integration-tests/src/step_definitions/common/common.steps.ts
- source/packages/integration-tests/src/support/assetLibrary_hooks.ts
Fixing lint errors and warnings seen here: [https://github.com/aws/aws-connected-device-framework/actions/runs/5625609515](https://github.com/aws/aws-connected-device-framework/actions/runs/5625609515)
> fix: addressing lint errors/warnings

- source/packages/libraries/core/deployment-helper/package.json
Deployment helper needs to be public as well to generate artifacts.
> fix: make deployment helper public

- buildspec.yml
- source/common/config/rush/pnpm-lock.yaml
- source/common/config/rush/repo-state.json
- source/packages/libraries/core/version/package.json
- Lock the PNPM version to `pnpm@8`
- Add missing dev dependency
> Fix broken pipeline

- source/packages/libraries/core/attribution/package.json
- source/packages/services/assetlibrary-export/package.json
- source/packages/services/assetlibrary/package.json
- source/packages/services/assetlibraryhistory/package.json
- source/packages/services/bulkcerts/package.json
- source/packages/services/certificateactivator/package.json
- source/packages/services/certificatevendor/package.json
- source/packages/services/command-and-control/package.json
- source/packages/services/device-patcher/package.json
- source/packages/services/events-alerts/package.json
- source/packages/services/events-processor/package.json
- source/packages/services/greengrass2-provisioning/package.json
- source/packages/services/organization-manager/package.json
- source/packages/services/provisioning/package.json
Moving CDF attribution dependency to devDeps
> refactor: move CDF attribution dependency to devDeps
